version: 2
jobs:
  build:
    docker:
     - image: circleci/node:11
     steps:
      - checkout
      - run:
          name: install-npm
          command: 'sudo npm install -g'
      - run:
          name: test
          command: npm test db format oauth
      - run:
          name: lint
          command: npm lint